(define (rataan uts uas prak)
  (/ (+ uts uas prak) 3))
(define (mutu rataan)
 (if (< rataan 20) (display "E")
 (if (< rataan 40) (display "D")
 (if (< rataan 60) (display "C")
 (if (< rataan 80) (display "B")
 (if (< rataan 100) (display "A")
 )))))
)
(mutu(rataan (read) (read) (read)))
(newline)
